# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 04:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('content', models.TextField()),
                ('write_date', models.DateTimeField(auto_now_add=True, verbose_name='\u5199\u4f5c\u65f6\u95f4')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u4fee\u6539\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u5206\u7c7b\u540d')),
                ('p_catagory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='myblog.Category', verbose_name='\u4e0a\u7ea7\u5206\u7c7b')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_to_me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='\u8bc4\u8bba\u65f6\u95f4')),
                ('content', models.CharField(max_length=200, verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
            ],
            options={
                'ordering': ['-comment_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment_to_article',
            fields=[
                ('comment_to_me_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myblog.Comment_to_me')),
            ],
            bases=('myblog.comment_to_me',),
        ),
        migrations.AddField(
            model_name='comment_to_me',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.Category', verbose_name='\u6240\u5c5e\u5206\u7c7b'),
        ),
        migrations.AddField(
            model_name='comment_to_article',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.Article', verbose_name='\u88ab\u8bc4\u8bba\u6587\u7ae0'),
        ),
    ]
